### ISSUE TITLE
menu bar scrolling away

### ISSUE THREAD

**Issue by marc-guenther** [jenkins-contrib-themes/jenkins-material-theme#50]
I really love this theme, so much nicer than the default.

So this is really nitpicking, but we have these two bars on top of the screen, the one with the Jenkins logo, and the menu bar below. In original Jenkins layout, when you scroll down, the Jenkins logo bar disappears, and the menu bar stays at the top. Here, the (quite useledd) big green Jenkins bar stays, and the (very useful) menu bar scrolls away.

Can this be reversed?

**Comment by afonsof** [comment]
Hi @marc-guenther, thanks for filling this issue. Unfortunately I guess this is so hard to do due to some tricks I had to do in order to increase the titlebar height. I experienced too many problems with titlebar vs breadcrumbs vs z-index popups in the past.
Would you like to try to write a patch for this? We'd be more than happy to walk you through the steps involved.
