### ISSUE TITLE
Logo generator feature enhancement?

### ISSUE THREAD

**Issue by jonten** [jenkins-contrib-themes/jenkins-material-theme#54]
Hi!

First of all I want to congratulate you for creating the best looking Jenkins theme available :)

I also wanted to ask if it would be much work for you to make the logo generator also allow the user to enter a custom color for the header and link texts?

Best regards,

//Jon

**Comment by vikas027** [comment]
+1 to give an option to replace the default Jenkins Logo.

Indeed, a pretty clean looking theme. :+1:

**Comment by Signus** [comment]
+1 for allowing the user to pick colors. I would even say given a logo, create a color scheme based off of the image, but I digress.

The user should have power to change their color schemes as needed, although for best viewing experience they should be limited to change a few colors that define the whole scheme (that way the color palette isn't all over the place).

Suggestions:
- Custom pick color for header
- Custom pick color for links
- Custom pick color for console output background/foreground color(s)

**Comment by outime** [comment]
Right now it's implemented so that when you upload the logo [in the theme webpage](http://jenkins-contrib-themes.github.io/jenkins-material-theme/), there's [a small JS script](http://i.imgur.com/bC9TMgV.png) that will convert the uploaded image to base64 and adds some more CSS to the standard one - then it gives you the final file that uses the custom logo. Overriding header and link text colors is easy - adding a couple fields to the webpage and few more CSS lines.

For generating color palettes, [this might help](https://github.com/lokesh/color-thief/).

**Comment by afonsof** [comment]
Now it's possible to also choose the theme color. Check it out: http://jenkins-contrib-themes.github.io/jenkins-material-theme/

![image](https://cloud.githubusercontent.com/assets/805511/15797839/3d5fc8e0-29f3-11e6-886c-2289747730f5.png)
